Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "springboot"
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end
  
  # Synchronisation du dossier contenant l'application
  config.vm.synced_folder "../banking_App", "/home/vagrant/banking_App"
end