Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "nginx"
  config.vm.network "private_network", ip: "192.168.33.12"
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end
  
  config.vm.provision "shell", path: "provision.sh"
end